name: Build
on: 
  workflow_dispatch:
concurrency:
  group: Build
  cancel-in-progress: true

jobs:
  build:
    name: Build nakedjsx.github.io
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          check-latest: true

      - shell: bash
        run: git config --global core.autocrlf input
      
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build Documentation
        shell: bash
        run: |
          cd nakedjsx.github.io/documentation
          npx nakedjsx src --output-dir dist
